projectMovie/movies/urls.py
from django.urls import path
from .views import SerieListView, SerieDetailView, SerieUpdateView, SerieCreateView, SerieDeleteView
from .views import FilmList, FilmDetailView, FilmCreate, FilmUpdate, FilmDelete, home, connexion, showimage
from .views import RealisateurListView, RealisateurDetailView, RealisateurUpdateView, RealisateurCreateView,RealisateurDeleteView

app_name = 'movies' # Encapsule les urls de ce module dans le namespace musique

urlpatterns = [
    path('series', SerieListView.as_view(), name='serie_list'),
    path('series/', SerieListView.as_view(), name='serie_list'),
    path('series/<int:pk>', SerieDetailView.as_view(), name='serie_detail'),
    path('series/edit/<int:pk>', SerieUpdateView.as_view(), name='serie_edit'),
    path('series/create', SerieCreateView.as_view(), name='serie_create'),
    path('series/delete/<int:pk>', SerieDeleteView.as_view(), name='serie_delete'),
    path('home', home, name='home'),
    path('home/', home, name='home'),
    path('films', FilmList.as_view(), name='film_list'),
    path('films/', FilmList.as_view(), name='film_list'),
    path('films/<int:pk>', FilmDetailView.as_view(), name='film_details'),
    path('films/add', FilmCreate.as_view(), name='nouveau_film'),
    path('films/update/<int:pk>', FilmUpdate.as_view(), name='modif_film'),
    path('films/delete/<int:pk>', FilmDelete.as_view(), name='sup_film'),
    path('realisateur', RealisateurListView.as_view(), name='realisateur_list'),
    path('realisateur/', RealisateurListView.as_view(), name='realisateur_list'),
    path('realisateur/<int:pk>', RealisateurDetailView.as_view(), name='realisateur_detail'),
    path('realisateur/edit/<int:pk>', RealisateurUpdateView.as_view(), name='realisateur_edit'),
    path('realisateur/create', RealisateurCreateView.as_view(), name='realisateur_create'),
    path('realisateur/delete/<int:pk>', RealisateurDeleteView.as_view(), name='realisateur_delete'),
    path('login/', connexion, name='connexion'),
    path('img/', showimage, name='image')
    # path('series', test, name='home-serie')
]

projectMovie/projectMovie/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include(('movies.urls', 'movies'), namespace='movies'))
] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

projectMovie/movies/models.py
from django.db import models
from django.shortcuts import redirect
from datetime import datetime

# Create your models here.

class Image(models.Model):
    name= models.CharField(max_length=500)
    imagefile= models.FileField(upload_to='media/images/', null=True, verbose_name="")

    def __str__(self):
        return self.name 


class Realisateur (models.Model):
    nom = models.CharField(max_length=64)
    description = models.CharField(max_length=2500, default="no description") 
    link_img = models.CharField(max_length=350, null=True) 

    def __str__ (self) :
        return self.nom

    @classmethod
    def getRealbyNom (cls, nom) : 
        return Realisateur.objects.get(nom = nom)


class Film (models.Model):
    nom = models.CharField(max_length=64)
    sortie = models.DateField(null=True, default=datetime.now())
    description = models.CharField(max_length=2500)
    realisateurs = models.ManyToManyField(Realisateur, related_name="films")
    img = models.ForeignKey(Image, on_delete=models.CASCADE, null=True)
    link_img = models.CharField(max_length=350, null=True)

    def __str__ (self) :
        return self.nom 

    def get_absolute_url(self): # new
        return redirect('http://localhost:8000/movies/films')


class Serie(models.Model):
    nom = models.CharField(max_length=64)
    sortie = models.DateField(null=True, default=datetime.now())
    description = models.CharField(max_length=2500)
    nb_saison = models.IntegerField()
    realisateurs = models.ManyToManyField(Realisateur, related_name="series")
    image = models.ForeignKey(Image, on_delete=models.CASCADE, null=True)
    link_img = models.CharField(max_length=350, null=True)
    def __str__ (self) :
        return self.nom

projectMovie/movies/forms.py
from django import forms
from .models import Image

class ImageForm(forms.ModelForm):
    class Meta:
        model= Image
        fields= ["name", "imagefile"]

projectMovie/movies/views/viewFilm.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.http import HttpResponse
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from movies.models import Film, Realisateur

# Create your views here.

class FilmList(ListView):
    model = Film

class FilmDetailView(DetailView):
    model = Film

class FilmCreate(CreateView):
    model = Film
    fields = ['nom', 'description', 'sortie', 'realisateurs', 'img']
    success_url = reverse_lazy('movies:film_list')

class FilmUpdate(UpdateView):
    model = Film
    fields = ['nom', 'description', 'sortie', 'realisateurs', 'img']
    template_name_suffix = '_update_form'
    success_url = reverse_lazy('movies:film_list')

class FilmDelete(DeleteView):
    model = Film
    success_url = reverse_lazy('movies:film_list')

projectMovie/movies/views/viewHome.py
from django.shortcuts import render
from django.http import HttpResponse
from movies.models import Image
from movies.forms import ImageForm

# Create your views here.

def home(request) :
    return render(request, template_name='home.html')


def connexion(request) :
    return render(request, template_name='login.html')


def showimage(request):
    image= Image.objects.all()
    form= ImageForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        form.save()
    context= {'image': image,
              'form': form
              }
    return render(request, template_name='images.html', context=context)

projectMovie/movies/views/viewReal.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import DetailView, ListView, UpdateView, CreateView, DeleteView
from movies.models import Realisateur
from django.contrib import messages
from django.shortcuts import reverse
# Create your views here.

class RealisateurListView(ListView):
    model = Realisateur

class RealisateurDetailView(DetailView):
    model = Realisateur

class RealisateurDeleteView(DeleteView):
    model = Realisateur
    template_name_suffix = '_delete'

    def get_success_url(self):
        messages.success(self.request, 'Realisateur Supprimé')
        return reverse('movies:realisateur_list')

class RealisateurUpdateView(UpdateView):
    model = Realisateur
    fields = ('nom',)
    template_name_suffix = '_edit'

    def get_success_url(self):
        messages.success(self.request, 'Realisateur Mise à jour')
        return reverse('movies:realisateur_list')

class RealisateurCreateView(CreateView):
    model = Realisateur
    fields = ('nom','description', 'link_img')
    template_name_suffix = '_create'

    def get_success_url(self):
        messages.success(self.request, 'Realisateur Mise à jour')
        return reverse('movies:realisateur_list')

projectMovie/movies/views/viewSerie.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.http import HttpResponse
from django.views.generic import DetailView, ListView, UpdateView, CreateView, DeleteView
from movies.models import Serie
from django.shortcuts import reverse
from django.contrib import messages

# Create your views here.

class SerieListView(ListView):
    model = Serie

class SerieDetailView(DetailView):
    model = Serie

class SerieDeleteView(DeleteView):
    model = Serie
    template_name_suffix = '_delete'
    
    def get_success_url(self):
        messages.success(self.request, 'Serie Supprimé')
        return reverse('movies:serie_list')

class SerieUpdateView(UpdateView):
    model = Serie
    fields = ('nom','sortie','description','nb_saison','realisateurs', 'image')
    template_name_suffix = '_edit'

    def get_success_url(self):
        messages.success(self.request, 'Serie Mise à jour')
        return reverse('movies:serie_list')

class SerieCreateView(CreateView):
    model = Serie
    fields = ('nom','sortie','description','nb_saison','realisateurs', 'image')
    template_name_suffix = '_create'

    def get_success_url(self):
        messages.success(self.request, 'Serie Mise à jour')
        return reverse('movies:serie_list')

projectMovie/movies/templates/base.html
{% load static %}
<html  lang="fr">
    <head>
        <meta charset="utf-8">
        <title>
            {% block title %}
            {% endblock %}
        </title>
        {% block styles %}
            <link rel="stylesheet"href="{%static 'node_modules/bootstrap/dist/css/bootstrap.min.css'%}">
            <link rel="stylesheet" href="{% static 'css/globalcss.css' %}">
        {% endblock %}
    </head>
    <body style="background-color: #eaecef;">
            {% block nav %}
            <nav class="navbar navbar-expand-lg navbar-light bg-warning">
                <img src="{% static 'img/logo_site.png'%}" alt="logo du site"  style="width:150px; height:50px">
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                  <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                      <a class="nav-link" href="{% url 'movies:home' %}"> Accueil</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'movies:film_list' %}">Films</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'movies:serie_list' %}">Series</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'movies:realisateur_list' %}">Realisateurs</a>
                    </li>
                  </ul>
                </div>
                <a class="col" href="{% url 'movies:connexion' %}"><img src="{%static 'img/login.png'%}" alt="image de connexion" class="rounded float-right" style="width:60px; height:60px"></a>
              </nav>
            {% endblock %}
            <main role="main"class="containertop-pushed">
                <div class="jumbotron">
                    {% block content %}
                    {% endblock %}
                </div>
            </main>
            <footer class="bg-warning">
                <div class="container">
                    <br>
                    <div class="row" style="text-align: center;">
                        <div class="col"> <a href=""><img src="{%static 'img/SocialNetworks/facebook.png'%}" alt="Facebook" style="width:80px; height:80px"></a> </div>
                        <div class="col"> <a href=""><img src="{%static 'img/SocialNetworks/twitter.png'%}" alt="Twitter" style="width:80px; height:80px"></a> </div>
                        <div class="col"> <a href=""><img src="{%static 'img/SocialNetworks/instagram.png'%}" alt="Instagram" style="width:80px; height:80px"></a> </div>
                        <div class="col"> <a href=""><img src="{%static 'img/SocialNetworks/youtube.png'%}" alt="Youtube" style="width:80px; height:80px"></a> </div>
                        <div class="col"> <a href=""><img src="{%static 'img/SocialNetworks/twitch.png'%}" alt="Twitch" style="width:80px; height:80px"></a> </div>
                        <div class="col"> <a href=""><img src="{%static 'img/SocialNetworks/snapchat.png'%}" alt="Snapchat" style="width:80px; height:80px"></a> </div>
                    </div>
                    <br><br>
                    <div class="row" style="text-align: center;">
                        <div class="col"><a href="" class="badge badge-warning"> <b> Aide</b> </a></div>
                        <div class="col"><a href="" class="badge badge-warning"> <b> Qui sommes nous ?</b> </a> </div>
                        <div class="col"> <a href="" class="badge badge-warning"> <b> Rejoignez-nous</b> </a> </div>
                        <div class="col"> <a href="" class="badge badge-warning"> <b> CGU</b> </a> </div>
                        <div class="col"> <a href="" class="badge badge-warning"> <b> Données Personnelles</b> </a> </div>
                        <div class="col"> <a href="" class="badge badge-warning"> <b> Nous contacter</b> </a> </div>
                    </div>
                    <br>
                    <p style="text-align: center; font-size: smaller; color:grey">Copyright 2020 @ProjectMovie .Inc <br><br></p>  
                </div>
            </footer>
        {% block js %}
            <script src="{%static 'node_modules/bootstrap/dist/js/bootstrap.min.js'%}"></script>
            <script src="{%static 'node_modules/jquery/dist/jquery.slim.min.js'%}"></script>
            <script src="{%static 'node_modules/popper.js/dist/popper.min.js'%}"></script>
        {% endblock %}
    </body>
</html>

projectMovie/movies/templates/images.html
{% extends "base.html"%}

{% load static %}

{% block title %}
    Ajout d'une image
{% endblock %}
{% block styles %}
    {{ block.super }}
{% endblock %}
{% block content%}

    <h1>Ajouter une image pour illustrer un Film ou une Série</h1>
    <form enctype="multipart/form-data" method="POST" action="">
    {% csrf_token %}
    {{ form.as_p }}
    <br>
    <input type="submit" class="btn btn-outline-warning" value="Ajouter l'image à la BD"/><br><br><br>
    </form>
    <a href="{% url 'movies:home'%}"><button class="btn btn-warning">Accueil</button></a>
    <a href="{% url 'movies:film_list'%}"><button class="btn btn-warning">Films</button></a>
    <a href="{% url 'movies:serie_list'%}"><button class="btn btn-warning">Séries</button></a>
{% endblock %}

projectMovie/movies/templates/movies/film_confirm_delete.html
{% extends "base.html"%}
{% block title %}
    Les Films
{% endblock %}
{% block styles %}
    {{ block.super }}
{% endblock %}
{% block content%}
    <div style="text-align: center;">
        <form method="post">{% csrf_token %}
            <p>Voulez vous vraiment supprimer <b>{{ object }} </b>?</p>
            <input type="submit" value="Confirmer" class="btn btn-outline-warning">
        </form>
        <a href="{% url 'movies:film_details' object.pk %}"><button class="btn btn-warning">Annuler</button></a>
    </div>
{% endblock %}

projectMovie/movies/templates/movies/film_detail.html
{% extends "base.html"%}
{% load static %}
{% block title %}
    Détails du Film
{% endblock %}
{% block styles %}
    {{ block.super }}
{% endblock %}
{% block content%}
        <div style="text-align: center;">
            <h1>Détails de <br><i>{{object.nom}}</i></h1><br><br>
            {% if film.link_img %}
                <img src="{{film.link_img}}" class="card-img-top" alt="image du Film" style="height: 500px; width:350px">
            {% else %}
                <img src="{% static 'media/'%}{{film.img.imagefile}}" class="card-img-top" alt="img Film" style="height: 500px; width:350px">
            {% endif %}<br> <br><br>
            <h4>Description</h4>
            <p style="max-width: 1000px; margin: auto;"> {{object.description}}</p><br><br>
            <h4>Sortie</h4>
            <p>{{object.sortie}}</p><br>
            <h4>Realisateur(s)</h4>
            <p>
                {% for realisateur in object.realisateurs.all %}
                <a href="{% url 'movies:realisateur_detail' realisateur.pk %}" style="color: black;">{{realisateur}}</a>
                {% endfor %}
            </p>
            <br>
            <p style="text-align: center;">
                <a href="{% url 'movies:modif_film' object.pk %}"><button class="btn btn-outline-warning">Modifier ce film</button></a>
                <a href="{% url 'movies:sup_film' object.pk %}"><button class="btn btn-outline-warning">Supprimer ce film</button></a>
            </p>
            <p style="text-align: center;">
                <a href="{% url 'movies:film_list' %}"><button class="btn btn-warning">Retour aux films</button></a>
            </p>
        </div>
{% endblock %}

projectMovie/movies/templates/movies/film_form.html
{% extends "base.html"%}
{% block title %}
    Ajouter un film
{% endblock %}
{% block styles %}
    {{ block.super }}
{% endblock %}
{% block content%}
<a href="{% url 'movies:film_list'%}"><button class="btn btn-warning">Retour</button></a><br><br><br>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <br><p>Vous pouvez aussi ajouter : </p>
    <ul>
        <li class="badge badge-warning"><a href="{% url 'movies:image'%} " style=" color:cornsilk;"> Une Image </a></li>
        <li class="badge badge-warning"><a href="{% url 'movies:realisateur_create'%}" style=" color:cornsilk;"> Un Réalisateur </a></li>
    </ul>
    <br><input type="submit" class="btn btn-outline-warning" value="Ajouter le Film">
    
</form>
{% endblock %}

projectMovie/movies/templates/movies/film_list.html
{% extends "base.html"%}

{% load static %}

{% block title %}
    Les Films
{% endblock %}
{% block styles %}
    {{ block.super }}
{% endblock %}
{% block content%}
        <h1 style="text-align: center; font-size:70px;"> Films </h1><br>
        <div class="d-flex flex-row flex-wrap justify-content-center">
            {% for film in object_list %}
                <a href="{% url 'movies:film_details' film.pk%}" style="text-decoration: none;">
                    <div class=" mb-4 px-5 py-5 align-items-center mx-3" style="width : 350px;text-align: center;">
                        {% if film.link_img %}
                            <img src="{{film.link_img}}" class="card-img-top" alt="image du Film"  style="height: 500px; width:350px">
                        {% else %}
                            <img src="{% static 'media/'%}{{film.img.imagefile}}" class="card-img-top" alt="img Film"  style="height: 500px; width:350px">
                        {% endif %}
                        <div class="card-body">
                            <b> <h5 style="color:orange; text-decoration: none;" class="card-title">{{film.nom}}</h5></b>
                            <p class="card-text" style="color: black;">{{film.description}}</p>
                            <a href="{% url 'movies:film_details' film.pk%}"> <button class="btn btn-outline-warning">Détails</button></a>
                            <a href="{% url 'movies:modif_film' film.pk%}"> <button class="btn btn-outline-warning">Modifier</button></a>
                        </div>
                    </div>
                </a>
            {% endfor %}
        </div>
        <p style="text-align: center;">
            <br><a href="{% url 'movies:nouveau_film' %}"><button class="btn btn-warning">Ajouter un film</button></a>
        </p>
{% endblock %}

projectMovie/movies/templates/movies/film_update_form.html
{% extends "base.html"%}
{% block title %}
    Modifier le Film
{% endblock %}
{% block styles %}
    {{ block.super }}
{% endblock %}
{% block content%}
<a href="{% url 'movies:film_details' object.pk %}"><button class="btn btn-warning">Retour</button></a><br><br><br>
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <br><input type="submit" class="btn btn-outline-warning" value="Valider les modifications">
</form>
{% endblock %}

projectMovie/movies/templates/movies/realisateur_detail.html
{% extends "base.html"%}
{% block title %}
Détails de la réalisateur
{% endblock %}
{% block styles %}
{{ block.super }}
{% endblock %}
{% block content%}
<div style="text-align: center;">
    <h1>Détails de <br><i>{{object.nom}} </i></h1><br><br>
    {% if object.films.all %}
        <h4>Film(s) réalisé(s)</h4>
        <ul style="list-style: none;">
            {% for film in object.films.all %}
                <li><a href="{% url 'movies:film_details' film.pk %}" style="color: black;">{{film}}</a></li>
            {% endfor %}
        </ul>
    {% endif %}
    <br>
    {% if object.series.alls %}
        <h4>Série(s) réalisée(s)</h4>
        <ul style="list-style: none;">
            {% for serie in object.series.all %}
            <li><a href="{% url 'movies:serie_detail' serie.pk %}" style="color: black;">{{serie}}</a></li>
            {% endfor %}
        </ul>
    {% endif %}
    <br>
    <p style="text-align: center;">
        <a href="{% url 'movies:realisateur_edit' object.pk %}"><button class="btn btn-outline-warning">Modifier ce réalisateur</button></a>
        <a href="{% url 'movies:realisateur_delete' object.pk %}"><button class="btn btn-outline-warning">Supprimer ce réalisateur</button></a>
    </p>
    <p style="text-align: center;">
        <a href="{% url 'movies:realisateur_list' %}"><button class="btn btn-warning">Retour aux réalisateurs</button></a>
    </p>
</div>
{% endblock %}

projectMovie/movies/templates/movies/realisateur_edit.html
{% extends "base.html"%}

{% load crispy_forms_tags %}

{% block title %}
Modifier le Realisateur
{% endblock %}
{% block styles %}
{{ block.super }}
{% endblock %}
{% block content%}
<a href="{% url 'movies:realisateur_detail' object.pk %}"><button class="btn btn-warning">Retour</button></a><br><br><br>
<form method="post">{% csrf_token %}
    {{ form.nom|as_crispy_field }}
    <br><input type="submit" class="btn btn-outline-warning" value="Valider les modifications">
</form>
{% endblock %}

projectMovie/movies/templates/movies/realisateur_list.html
{% extends "base.html"%}
{% load static %}
{% block title %}
Les Realisateurs
{% endblock %}
{% block styles %}
{{ block.super }}
{% endblock %}
{% block content%}
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li style="list-style:none; color:red">{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
<h1 style="text-align: center; font-size:70px;"> Realisateur </h1><br>
<div class="d-flex flex-row flex-wrap justify-content-center">
    {% for real in object_list %}
        <div class=" mb-4 px-5 py-5 align-items-center" style="width: 22rem; text-align: center;">
            <div class="card-body">
                <b> <h5 style="color:orange; text-decoration: none;" class="card-title">{{real.nom}}</h5></b>
                <p class="card-text" style="color: black;">{{real.description}}</p>
                <a href="{% url 'movies:realisateur_detail' real.pk%}"> <button class="btn btn-outline-warning">Détails</button></a>
                <a href="{% url 'movies:realisateur_edit' real.pk%}"> <button class="btn btn-outline-warning">Modifier</button></a>
            </div>
        </div>
    {% endfor %}
</div>
<p style="text-align: center;">
    <br><a href="{% url 'movies:realisateur_create' %}"><button class="btn btn-warning">Ajouter un realisateur</button></a>
</p>
{% endblock %}

projectMovie/movies/templates/movies/serie_create.html
{% extends "base.html"%}
{% load crispy_forms_tags %}
{% block title %}
    Ajouter une série
{% endblock %}
{% block styles %}
    {{ block.super }}
{% endblock %}
{% block content%}
<a href="{% url 'movies:serie_list'%}"><button class="btn btn-warning">Retour</button></a><br><br><br>
<form method="post">
    {% csrf_token %}
    {{ form.nom|as_crispy_field }}
    {{ form.sortie|as_crispy_field }}
    {{ form.description|as_crispy_field }}
    {{ form.nb_saison|as_crispy_field }}
    {{ form.realisateurs|as_crispy_field }}
    {{ form.image|as_crispy_field }}
    <br><p>Vous pouvez aussi ajouter : </p>
    <ul>
        <li class="badge badge-warning"><a href="{% url 'movies:image'%} " style=" color:cornsilk;"> Une Image </a></li>
        <li class="badge badge-warning"><a href="{% url 'movies:realisateur_create'%}" style=" color:cornsilk;"> Un Réalisateur </a></li>
    </ul>
    <br><input type="submit" class="btn btn-outline-warning" value="Ajouter la série">
</form>
{% endblock %}

projectMovie/movies/templates/movies/serie_delete.html
{% extends "base.html"%}
{% block title %}
    Les Films
{% endblock %}
{% block styles %}
    {{ block.super }}
{% endblock %}
{% block content%}
    <div style="text-align: center;">
        <form method="post">{% csrf_token %}
            <p>Voulez vous vraiment supprimer <b>{{ object }} </b>?</p>
            <input type="submit" value="Confirmer" class="btn btn-outline-warning">
        </form>
        <a href="{% url 'movies:serie_detail' object.pk %}"><button class="btn btn-warning">Annuler</button></a>
    </div>
{% endblock %}

projectMovie/movies/templates/movies/serie_detail.html
{% extends "base.html"%}
{% load static %}
    {% block title %}
        Détails de la série
    {% endblock %}
    {% block styles %}
        {{ block.super }}
    {% endblock %}
    {% block content%}
            <div style="text-align: center;">
                <h1>Détails de <br><i>{{object.nom}}</i></h1><br><br>
                {% if object.link_img %}
                    <img src="{{object.link_img}}" class="card-img-top" alt="image du Film" style="height: 500px; width:350px">
                {% else %}
                    <img src="{% static 'media/'%}{{object.img.imagefile}}" class="card-img-top" alt="img Film" style="height: 500px; width:350px">
                {% endif %}<br> <br><br>
                <h4>Description</h4>
                <p style="max-width: 1000px; margin: auto;"> {{object.description}}</p><br><br>
                <h4>Sortie</h4>
                <p>{{object.sortie}}</p><br>
                <h4>Nombre de Saison</h4>
                <p>{{object.nb_saison}}</p><br>
                <h4>Realisateur(s)</h4>
                <p>
                    {% for realisateur in object.realisateurs.all %}
                    <a href="{% url 'movies:realisateur_detail' realisateur.pk %}" style="color: black;">{{realisateur}}</a>
                    {% endfor %}
                </p>
                <br>
                <p style="text-align: center;">
                    <a href="{% url 'movies:serie_edit' object.pk %}"><button class="btn btn-outline-warning">Modifier cette série</button></a>
                    <a href="{% url 'movies:serie_delete' object.pk %}"><button class="btn btn-outline-warning">Supprimer cette série</button></a>
                </p>
                <p style="text-align: center;">
                    <a href="{% url 'movies:serie_list' %}"><button class="btn btn-warning">Retour aux Séries</button></a>
                </p>
            </div>
    {% endblock %}

projectMovie/movies/templates/movies/serie_edit.html
{% extends "base.html"%}

{% load crispy_forms_tags %}

{% block title %}
    Modifier la Série
{% endblock %}
{% block styles %}
    {{ block.super }}
{% endblock %}
{% block content%}
<a href="{% url 'movies:serie_detail' object.pk %}"><button class="btn btn-warning">Retour</button></a><br><br><br>
<form method="post">{% csrf_token %}
    {{ form.nom|as_crispy_field }}
    {{ form.sortie|as_crispy_field }}
    {{ form.description|as_crispy_field }}
    {{ form.nb_saison|as_crispy_field }}
    {{ form.realisateurs|as_crispy_field }}
    {{ form.image|as_crispy_field }}
    <br><input type="submit" class="btn btn-outline-warning" value="Valider les modifications">
</form>
{% endblock %}

projectMovie/movies/templates/movies/serie_list.html
{% extends "base.html"%}
{% load static %}
{% block title %}
    Les Séries
{% endblock %}
{% block styles %}
    {{ block.super }}
{% endblock %}
{% block content%}
    <h1 style="text-align: center; font-size:70px;"> Séries </h1><br>
    <div class="d-flex flex-row flex-wrap justify-content-center">
        {% for serie in object_list %}
            <a href="{% url 'movies:serie_detail' serie.pk%}" style="text-decoration: none;"> 
                <div class=" mb-4 px-5 py-5 align-items-center" style="width: 22rem; text-align: center;">
                    {% if serie.link_img %}
                        <img src="{{serie.link_img}}" class="card-img-top" alt="image de la serie"  style="height: 500px; width:350px">
                    {% else %}
                        <img src="{% static 'media/'%}{{serie.img.imagefile}}" class="card-img-top" alt="image de la serie"  style="height: 500px; width:350px">
                    {% endif %}
                    <div class="card-body">
                        <b> <h5 style="color:orange; text-decoration: none;" class="card-title">{{serie.nom}}</h5></b>
                        <p class="card-text" style="color: black;">{{serie.description}}</p>
                        <a href="{% url 'movies:serie_detail' serie.pk%}"> <button class="btn btn-outline-warning">Détails</button></a>
                        <a href="{% url 'movies:serie_edit' serie.pk%}"> <button class="btn btn-outline-warning">Modifier</button></a>
                    </div>
                </div>
            </a>
        {% endfor %}
    </div>
        <p style="text-align: center;">
            <br><a href="{% url 'movies:serie_create' %}"><button class="btn btn-warning">Ajouter une série</button></a>
        </p>
{% endblock %}